[package]
authors = ["Jake Goulding <jake.goulding@gmail.com>"]
name = "evaluate"
version = "0.1.0"
edition = "2018"

[dependencies]
getopts = "0.2.4"
sxd-document = "0.3.0"
sxd-xpath = { path = ".." }
